-- CreateTable
CREATE TABLE "Meals" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "fnum" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
